version: '3'
services:
  rabbit_filamensagens:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file: processador-conteudo-filamensageria/.env
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo_conteudo_arquivos:
    container_name: mongo_4.4.1
    image: mongo:4.4.1
    restart: unless-stopped
    env_file: processador-conteudo-filamensageria/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    ports:
      - "27017:27017"